
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://loclahost:5432/postgres
    username: user
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
